<body>
<h2 class="text-center my-5">Cagnotte</h2>

<?php //if($item->photoPath !== null): ?>

<form method="POST" action="<?= $router->pathFor('itemModif', ['id'=> $id, 'idItem' => $idItem])?>">
    <div class="form-group">
        <label for="inputTitle">Nom*</label>
        <input type="text" name="itemName" class="form-control" id="inputTitle">
    </div>
    <div class="form-group">
        <label for="comment">Description*</label>
        <textarea class="form-control" rows="5" id="comment" name="description"></textarea>
    </div>
    Les champs marqués d'un astérisque sont obligatoires.
    <button type="submit" class="btn btn-primary float-right">Modifier</button>
</form>
</body>