<?php if(!$isCagnotte): ?>
    <form method="POST" action="<?= $router->pathFor('cagnotteCreate', ['id'=> $id, 'idItem' => $idItem])?>">
        <h2 class="text-center my-5">Cagnotte de <?= $itemName ?></h2>
        <div class="col text-center">
            <p>Voulez-vous créer une cagnotte pour cet item ?</p>
            <button type="submit" class="btn btn-primary">Creer une cagnotte</button>
        </div>
    </form>
<?php else: ?>

    <?php $sum = 0; ?>
    <div class="card text-center">
        <div class="card-header">
            Cagnotte
        </div>
        <div class="card-body">
            <h5 class="card-title"><?= $itemName ?></h5>
            <?php if(isset($photoPath)): ?>
                <img src="<?= $rootUri . "/" . urldecode($photoPath) ?>" width="150px" height="150px">
            <?php endif; ?>
            <h3>Prix : <?= $prix ?> $</h3>
            <br></br>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Email des participants</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($participants as $participant): ?>
                    <tr>
                        <td><?= $participant->emailParticipant ?> : <?= $participant->somme ?> $</td>
                        <?php $sum += $participant->somme; ?>
                    </tr>
                <?php endforeach;?>
                </tbody>
            </table>
            <br></br>
            <?php if($prix-$sum > 0): ?>
                <h3>Reste à payer : <?= $prix-$sum; ?> $</h3>
                <br></br>
                <a data-toggle="modal" href="#participate" class="btn btn-primary">Participer</a><br><br>
            <?php else: ?>
                <h1>Prix de l'item atteint !</h1>
            <?php endif; ?>
        </div>
        <div class="card-footer text-muted">

        </div>
    </div>


        <div class="modal fade" id="participate" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Participer à la cagnotte</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form method="POST" action="<?= $router->pathFor('participerCagnotte', ['id'=> $id, 'idItem' => $idItem]) ?>">
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="inputPrice">Somme à verser</label>
                                <input type="number" max="<?= $prix-$sum ?>" step="0.01" min="0" class="form-control" id="inputPrice" name="somme" value="" required>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                            <button type="submit" class="btn btn-primary">Participer</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>



<?php endif; ?>
