<body>
<h2 class="text-center my-5">Création d'item</h2>
<form method="POST" action="<?= $router->pathFor('itemCreate') ?>">
    <div class="form-group">
        <label for="inputTitle">Nom*</label>
        <input type="text" name="itemName" class="form-control" id="inputTitle" required>
    </div>
    <div class="form-group">
        <label for="textarea">Description</label>
        <textarea class="form-control" id="textarea" rows="3" name="description"></textarea>
    </div>
    Les champs marqués d'un astérisque sont obligatoires.
    <button type="submit" class="btn btn-primary float-right">Envoyer</button>
</form>
</body>