<body>
    <h2 class="text-center my-5">Création de liste</h2>
    <form method="POST" action="<?= $router->pathFor('listeCreate') ?>">
        <div class="form-group">
            <label for="inputTitle">Titre*</label>
            <input type="text" name="listName" class="form-control" id="inputTitle" required>
        </div>
        <div class="form-group">
            <label for="inputDateExpi">Date d'expiration*</label>
            <input type="date" name="limitDate" class="form-control" id="inputDateExpi" required>
        </div>
        <div class="form-group">
            <label for="textarea">Description</label>
            <textarea class="form-control" id="textarea" rows="3" name="description"></textarea>
        </div>
        <div class=form-group>
            <label for="public">Publique</label>
            <input type="checkbox" id="public" name="public" value="1">
        </div>
        Les champs marqués d'un astérisque sont obligatoires.
        <button type="submit" class="btn btn-primary float-right">Envoyer</button>
    </form>
</body>

