<body>
    <h2 class="text-center my-5">Création de liste</h2>
    <form method="POST" action="">
        <div class="form-group">
            <label for="inputTitle">Titre*</label>
            <input type="text" name="titre" class="form-control" id="inputTitle" required>
        </div>
        <div class="form-group">
            <label for="inputDateExpi">Date d'expiration*</label>
            <input type="date" name="dateExpi" class="form-control" id="inputDateExpi" required>
        </div>
        <div class="form-group">
            <label for="textarea">Description</label>
            <textarea class="form-control" id="textarea" rows="3" name="descr"></textarea>
        </div>
        Les champs marqués d'un astérisque sont obligatoires.
        <button type="submit" class="btn btn-primary float-right">Envoyer</button>
    </form>
</body>

