<body>
<?php if(isset($_SESSION['user']['email'])) : ?>
    <?php if (isset($flash->getMessages()['wrongpassword'])) : ?>
        <?php foreach ($flash->getMessages()['wrongpassword'] as $m): ?>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong> <?= $m ?></strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
    <h1 class="text-center my-5">Suppression du compte</h1>
    <p class="text-center my-5">Attention, la suppression du compte entraine la suppression de vos listes</p>
        <form method="POST" action="<?= $router->pathFor('pageDelete') ?>">
            <div class="form-group">
                <label>Tapez votre mot de passe pour valider</label>
                <input type="text" name="password" class="form-control" id="inputConfirmation" required>
            </div>
            <button type="submit" class="btn btn-primary float-left">Supprimer définitivement le compte</button>
        </form>
<?php else : ?>
    <h2 class="text-center my-5">Vous n'êtes pas connecté</h2>
<?php endif; ?>
</body>
