<body>
<div class="header">
    <div class="container">
        <div class="navbar">
            <div class="logo">
                <img src="images/logo-mywishlist.png" width="50px">
            </div>

            <img src="images/panier.png" width="35px" height="30px">
        </div>

        <div class="row">
            <div class="col-2">
                <h1>MyWishlist</h1>
                <p>Wishez vos envies... <br>contribuez a celles de vos amis !</p>
                <a href="" class="btn">Wishez maintenant !</a>
            </div>
            <div class="col-2">
                <img src="images/happy.png" alt="">
            </div>
        </div>

    </div>
</div>

<div class="categories"></div>
