<body>
<?php if (isset($flash->getMessages()['mailexistant'])) : ?>
    <?php foreach ($flash->getMessages()['mailexistant'] as $m): ?>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong> <?= $m ?></strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<?php if (isset($flash->getMessages()['modifysuccess'])) : ?>
    <?php foreach ($flash->getMessages()['modifysuccess'] as $m): ?>
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            <strong> <?= $m ?></strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<?php if (isset($flash->getMessages()['deletesuccess'])) : ?>
    <?php foreach ($flash->getMessages()['deletesuccess'] as $m): ?>
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <strong> <?= $m ?></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endforeach; ?>
<?php endif; ?>
<?php if (isset($flash->getMessages()['goodregister'])) : ?>
    <?php foreach ($flash->getMessages()['goodregister'] as $m): ?>
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            <strong> <?= $m ?></strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<div class="header">
    <div class="container">
        <div class="navbar">
            <div class="logo">
                <img src="images/logo-mywishlist.png" width="50px">
            </div>
        </div>

        <div class="row">
            <div class="col-2">
                <h1>MyWishlist</h1>
                <br>
                <br>
                <p>Wishez vos envies... contribuez a celles de vos amis !</p>
                <a href="" class="btn btn-primary float-left">Wishez maintenant !</a>
            </div>
            <div class="col-2">
                <img src="images/happy.png" width="500px" height="750px" style="margin-left: 400%;">
            </div>
        </div>

    </div>
</div>

<div class="categories"></div>
