<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="<?= $rootUri ?>/public/css/bootstrap.css">
    <link rel="stylesheet" href="<?= $rootUri ?>/public/css/style.css">
    <link rel="stylesheet" href="<?= $rootUri ?>/public/css/fas-all.min.css">
    <title>MyWishlist</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="<?= $router->pathFor('home') ?>">MyWishList</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Listes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Profil</a>
                </li>
            </ul>
        </div>
        <div class="d-flex">
            <?php if(isset($_SESSION['user'])): ?>
                <a class="dropdown-item" href="#">Déconnexion</a>
            <?php else: ?>
                <a class="dropdown-item" href="<?= $router->pathFor('login') ?>">Connexion</a>
                <a class="dropdown-item" href="<?= $router->pathFor('register') ?>">Inscription</a>
            <?php endif; ?>


        </div>
    </div>
</nav>

<div class="container mt-3">
    <?= $content ?>
</div>

<script src="<?= $rootUri ?>/public/js/jquery.slim.min.js"></script>
<script src="<?= $rootUri ?>/public/js/popper.min.js"></script>
<script src="<?= $rootUri ?>/public/js/bootstrap.min.js"></script>
</body>
</html>