<?php if (isset($flash->getMessages()['setreservation'])) : ?>
    <?php foreach ($flash->getMessages()['setreservation'] as $m): ?>
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            <strong> <?= $m ?></strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<?php if ($liste->limitDate > date('Y-m-d H:i:s') || $liste->emailAuthor == $_SESSION['user']['email']): ?>
    <div class="card text-center">
        <div class="card-header">
            Votre liste
        </div>
        <div class="card-body">
            <h5 class="card-title"> <?= $liste->listName ?> </h5>
            <p class="card-text"> <?= $liste->description ?> </p>
            <?php if ($liste->isPublic == 1): ?>
                <p> Liste publique </p>
            <?php else : ?>
                <p> Liste privée</p>
            <?php endif; ?>
            <?php if (isset($_SESSION['user'])): ?>
                <?php if ($_SESSION['user']['email'] == $liste->emailAuthor): ?>
                <a data-toggle="modal" href="#addItem" class="btn btn-primary">Ajouter un item</a>
                <?php endif;?>
                <a data-toggle="modal" href="#addMessage" class="btn btn-primary">Laisser un message</a>
            <?php endif;?>
        </div>
        <div class="card-footer text-muted">
            Crée le <?= $liste->creationDate ?> - Expire le <?= $liste->limitDate ?>
        </div>
        <div class="row">
            <?php foreach ($items as $item) : ?>
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title"><?= $item->itemName ?></h5>
                            <p class="card-text"><?= $item->description ?></p>
                            <?php if ($item->photoPath !== null): ?>
                                <p><img src="<?= $rootUri . "/" . urldecode($item->photoPath) ?>" width="100px"
                                        height="100px"></p>
                            <?php endif; ?>
                            <p class="card-text"><?= $item->cout ?> $</p>
                            <?php if (isset($_SESSION['user'])): ?>
                                <?php if ($item->emailUser === null): ?>
                                    <?php if ($liste->limitDate < date('Y-m-d H:i:s')) : ?>
                                        L'item n'a pas été réservé
                                    <?php else: ?>
                                        <a href="<?= $router->pathFor('pageReservation', ['id' => $liste->idList, 'idItem' => $item->idItem]) ?>"
                                           class="btn btn-primary">Réserver</a>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php if ($liste->limitDate < date('Y-m-d H:i:s')) : ?>
                                        <?='Réservé par : ' . \mywishlist\model\User::where('email', '=', $item->emailUser)->first()->name; ?>
                                    <?php else: ?>
                                        L'item est réservé
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($item->emailUser !== null): ?>
                                    <a href="<?= $router->pathFor('showCagnotte', ['id' => $liste->idList, 'idItem' => $item->idItem]) ?>" class="btn btn-primary">Cagnotte</a>
                                <?php endif; ?>
                                <?php if ($_SESSION['user']['email'] == $liste->emailAuthor): ?>
                                    <a href="<?= $router->pathFor('pageModifItem', ['id' => $liste->idList, 'idItem' => $item->idItem]) ?>"
                                       class="btn btn-warning">Modifier</a>
                                    <a href="<?= $router->pathFor('deleteItem', ['id' => $liste->idList, 'idItem' => $item->idItem]) ?>"
                                       class="btn btn-danger">Supprimer</a>
                                <?php endif; ?>
                                <?php if($item->emailUser !== null):?>
                                    <br><br>
                                    <p class="card-text" style="text-decoration: underline">Message de réservation : </p>
                                    <label><?= \mywishlist\model\Item::query()->select("messageRes")->where('idItem', '=', $item->idItem)->pluck("messageRes")[0] ?></label>
                                <?php endif; ?>

                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="card-footer">
            Messages
        </div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Pseudo</th>
                <th scope="col">Message</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($messages as $message) :?>
            <tr>
                <td><?= $message->nameAuthor ?></td>
                <td><?= $message->message ?></td>
            </tr>
            <?php endforeach;?>
            </tbody>
        </table>

    </div>
<?php else: ?>
    Liste expirée
<?php endif; ?>
<div class="modal fade" id="addItem" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Création d'objet</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="<?= $router->pathFor('itemCreate', ['id' => $liste->idList]) ?>">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="inputName">Nom*</label>
                        <input type="text" name="name" class="form-control" id="inputName" placeholder="Nom de l'objet"
                               value="" required>
                    </div>
                    <div class="form-group">
                        <label for="inputDesc">Description</label>
                        <textarea class="form-control" id="inputDesc" rows="3" name="desc"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="inputUrl">Lien pour plus d'informations</label>
                        <input type="url" name="url" class="form-control" id="inputUrl" value="">
                    </div>
                    <div class="form-group">
                        <label for="inputPrice">Prix*</label>
                        <input type="number" step="0.01" min="0" class="form-control" id="inputPrice" name="prix"
                               value="" required>
                    </div>
                    Les champs marqués d'un astérisque sont obligatoires.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                    <button type="submit" class="btn btn-primary">Ajouter</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="addMessage" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Ajout d'un message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="<?= $router->pathFor('addMessage', ['id' => $liste->idList]) ?>">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="inputName">Nom*</label>
                        <input type="text" name="author" class="form-control" id="author" placeholder="Votre nom" value="Anonyme" required>
                    </div>
                    <div class="form-group">
                        <label for="inputDesc">Message*</label>
                        <textarea class="form-control" id="message" rows="3" name="message" style="resize :none"></textarea>
                    </div>
                    Les champs marqués d'un astérisque sont obligatoires.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                    <button type="submit" class="btn btn-primary">Ajouter</button>
                </div>
            </form>
        </div>
    </div>
</div>

