<body>
<h2 class="text-center my-5">Modification d'item</h2>

<form method="POST" action="<?= $router->pathFor('itemImageModif') ?>" enctype="multipart/form-data">
    <div class="file-loading">
        <input id="bfupload-b7" name="submit" multiple type="file" class="file" data-allowed-file-extensions='["png", "jpg", "jpeg"]'>
    </div>
    <button type="submit" class="btn btn-primary float-right">Modifier l'image</button>
</form>

<form method="POST" action="<?= $router->pathFor('itemModif') ?>">
    <div class="form-group">
        <label for="inputTitle">Nom*</label>
        <input type="text" name="email" class="form-control" id="inputEmail" required>
    </div>
    <div class="form-group">
        <label for="textarea">Password*</label>
        <input type="password" class="form-control" id="inputPassword" rows="3" name="password" required>
    </div>
    Les champs marqués d'un astérisque sont obligatoires.
    <button type="submit" class="btn btn-primary float-right">Se connecter</button>
</form>
</body>