<body>
<h2 class="text-center my-5">Modification d'item</h2>

<form method="POST" action="<?= $router->pathFor('itemImageModif', ['id'=> $id, 'idItem' => $idItem]) ?>" enctype="multipart/form-data">
    <div class="file-loading">
        <input id="bfupload-b7" name="submit" multiple type="file" class="file" data-allowed-file-extensions='["png", "jpg", "jpeg"]' required>
    </div>
    <button type="submit" class="btn btn-primary float-md-right">Modifier l'image</button>
</form>
<form method="POST" action="<?= $router->pathFor('deleteImageItem', ['id'=> $id, 'idItem' => $idItem]) ?>">
    <button type="submit" class="btn btn-danger float-md-right">Supprimer l'image</button>
</form>

<br><br><br>

<form method="POST" action="<?= $router->pathFor('itemModif', ['id'=> $id, 'idItem' => $idItem])?>">
    <div class="form-group">
        <label for="inputTitle">Nom*</label>
        <input type="text" name="itemName" class="form-control" id="inputTitle" required>
    </div>
    <div class="form-group">
        <label for="comment">Description*</label>
        <textarea class="form-control" rows="5" id="comment" name="description" required></textarea>
    </div>
    Les champs marqués d'un astérisque sont obligatoires.
    <button type="submit" class="btn btn-primary float-right">Modifier</button>
</form>
</body>